version: '3.8'

services:
  buckshout.redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend/WebAPI
      dockerfile: Dockerfile
    restart: always
    working_dir: /app/backend/WebAPI
    volumes:
      - ./backend:/app/backend
    ports:
      - "5000:5000"
      - "5001:5001"
    command: sh -c "dotnet run ../../build/Backshout.dll"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    command: sh -c "npm start"

  