export enum Event {
	CONNECTED = 'CONNECTED',
	DISCONNECTED = 'DISCONNECTED',
	RECONNECTED = 'RECONNECTED',

	ROOM_CREATED = 'ROOM_CREATED',
	ROOM_UPDATED = 'ROOM_UPDATED',
	ROOM_JOINED = 'ROOM_JOINED',
	ROOM_LEFT = 'ROOM_LEFT',
	ROOM_REMOVED = 'ROOM_REMOVED',

	GAME_STARTED = 'GAME_STARTED',
	GAME_PAUSED = 'GAME_PAUSED',
	GAME_RESUMED = 'GAME_RESUMED',
	GAME_FINISHED = 'GAME_FINISHED',

	MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
	MESSAGE_INITIATOR_RECEIVED = 'MESSAGE_INITIATOR_RECEIVED',

	PLAYER_CONNECTED = 'PLAYER_CONNECTED',
	PLAYER_DISCONNECTED = 'PLAYER_DISCONNECTED',
	PLAYER_LOST = 'PLAYER_LOST',
	PLAYER_WON = 'PLAYER_WON',

	ROUND_STARTED = 'ROUND_STARTED',
	ROUND_FINISHED = 'ROUND_FINISHED',

	TURN_CHANGED = 'TURN_CHANGED',
	TURN_EXPIRED = 'TURN_EXPIRED',
	TURN_SKIPPED = 'TURN_SKIPPED',

	RIFLE_LOADED = 'RIFLE_LOADED',
	RIFLE_AIMED = 'RIFLE_AIMED',
	RIFLE_SHOT = 'RIFLE_SHOT',
	RIFLE_PULLED = 'RIFLE_PULLED',
	RIFLE_EMPTIED = 'RIFLE_EMPTIED',

	ITEM_RECEIVED = 'ITEM_RECEIVED',
	ITEM_REMOVED = 'ITEM_REMOVED',
	ITEM_USED = 'ITEM_USED',
	ITEM_CANCELED = 'ITEM_CANCELED',
	ITEM_EFFECTED = 'ITEM_EFFECTED',
	ITEM_STOLEN = 'ITEM_STOLEN',

	TRAP_SET = 'TRAP_SET',
	TRAP_TRIGGERED = 'TRAP_TRIGGERED',

	MODIFIER_APPLIED = 'MODIFIER_APPLIED',
	MODIFIER_REMOVED = 'MODIFIER_REMOVED',

	DAMAGE_TAKEN = 'DAMAGE_TAKEN',
	HEALTH_RESTORED = 'HEALTH_RESTORED',
}
